---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atuin
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: atuin
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: atuin
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    # - ../../../../../common/components/httproute/common
  path: "./kubernetes/apps/base/services/atuin/app"
  postBuild:
    substitute:
      APP: atuin
      SUBDOMAIN: atuin
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      GROUP: Services
      DESCRIPTION: Shell history database
      PSQL_DB_USER: atuin
      PSQL_DB_NAME: atuin
      GATEWAY_SVC_NAME: atuin
      GATEWAY_SVC_PORT: "8888"
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 10m
