---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-cluster
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: mongodb-cluster
  dependsOn:
    - name: mongodb-operator
      namespace: operators
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: mongodb-cluster
      namespace: mongodb
  interval: 1h
  path: "./kubernetes/platform/base/mongodb/mongodb-cluster/app"
  postBuild:
    substitute:
      # inherited variables
      fastdata_storage: ${fastdata_storage}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: mongodb
  timeout: 5m
