apiVersion: v2
name: opencloud
description: Custom helm wrapper for Opencloud deployment
dependencies:
  - name: app-template
    version: "4.4.0"
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: app
  - name: common
    version: "0.0.1"
    repository: "file://../../library/common"
    import-values:
      - defaults
    # Other implicit dependencies are installed before this chart by fluxcd :
    # - external-secrets
version: 0.0.1
