---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
  - ./namespace.yaml
  - ./crowdsec/ks.yaml
  - ./traefik/ks.yaml
transformers:
  - ./transformers