---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: legacyapps
spec:
  releaseName: legacyapps
  chart:
    spec:
      chart: helm/apps/legacyapps
      interval: 12h
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3

  values:
    ingress:
      otoge:
        domain: ${second_domain}
      plex:
        domain: ${main_domain}
        externalUrl:
          web: ${main_domain_web}
          websecure: ${main_domain_websecure}
      bucket:
        domain: ${main_domain}
    legacyVmIp: ${legacy_vm_ip}

