---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: immich-oidc
      namespace: services
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: immich
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/oidc-application
    - ../../../../../common/components/cnpg/db
    - ../../../../../common/components/httproute/common
  path: "./kubernetes/apps/base/services/immich/app"
  postBuild:
    substitute:
      APP: immich
      SUBDOMAIN: photos
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      GROUP: Services
      DESCRIPTION: Photo backup service
      # Since there are multiple redirect urls, we use patches to complete this instead
      # REDIRECT_URL: "https://photos.${main_domain_websecure}/auth/login"
      REDIRECT_URL: ""
      PSQL_DB_USER: immich
      PSQL_DB_NAME: immich
      DATABASE_EXTENSIONS: |
        [
          { name: vector, ensure: present },
          { name: vchord, ensure: present },
          { name: cube, ensure: present },
          { name: earthdistance, ensure: present }
        ]
      GATEWAY_SVC_NAME: immich
      GATEWAY_SVC_PORT: "10323"
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
      quote: '"'
      patch_dns: ${quote}${patch_dns:=false}${quote}
      traefik_lb_ip: ${traefik_lb_ip}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
      second_domain: ${second_domain}
      auth_subdomain: ${auth_subdomain}
      gpu_runtime_class: ${gpu_runtime_class}
      nfs_server: ${nfs_server}
      nfs_path_immich: ${nfs_path_immich}
  patches:
    - target:
        kind: HelmRelease
        # match with label since name has variable in it
        labelSelector: homelab/auth-component=true
      patch: |
        - op: add
          path: '/spec/values/blueprint/groups/-'
          value:
            slug: "app: immich"
            bindID: "a776296c-b2f9-41c1-b7bf-112802f9572d" # arbitrary uuid
        - op: replace
          path: '/spec/values/blueprint/provider/oidc/redirectURL'
          value: ["https://photos.${main_domain_websecure}/auth/login", "app.immich:///oauth-callback"]

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 5m
