apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/staging
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: general-config
        optional: false
    substitute:
      quote: '"' # double quote var for boolean/numeral values