apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Values.immich.database.name }}
  namespace: {{ .Values.namespaces.postgresNamespace }}
spec:
  name: {{ .Values.immich.database.name }}
  ensure: present
  owner: {{ .Values.immich.database.user }}
  cluster:
    name: {{ .Values.database.postgres.clusterName }}
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
