---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName ${APP}-db-creds
spec:
  refreshPolicy: OnChange
  data:
  - secretKey: password
    remoteRef:
      key: *secretName
      property: password
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets
  target:
    # name: ${APP}-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/cluster: ${psql_cluster_name}
          cnpg.io/reload: "true"
      data:
        user: ${PSQL_DB_USER:=app}
        username: ${PSQL_DB_USER:=app}
        dbname: ${PSQL_DB_NAME:=app}
        host: "postgres-db-rw.${psql_database_namespace}.svc.cluster.local"
        password: "{{ .password }}"
        pgpass: "postgres-db-rw.${psql_database_namespace}.svc.cluster.local:5432:${PSQL_DB_NAME:=app}:${PSQL_DB_USER:=app}:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://postgres-db-rw.${psql_database_namespace}.svc.cluster.local:5432/${PSQL_DB_NAME:=app}?password={{ .password }}&user=${PSQL_DB_USER:=app}"
        uri: "postgres://${PSQL_DB_USER:=app}:{{ .password }}@postgres-db-rw.${psql_database_namespace}.svc.cluster.local:5432/${PSQL_DB_NAME:=app}"