---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
resources:
  - ./namespace.yaml
  - ./piraeus-operator/ks.yaml
transformers:
  - ./transformers