apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${SECRET_CREDS_NAME}
  labels:
    homelab/backup-resource: "true"
spec:
  refreshPolicy: OnChange
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "password"
  target:
    template:
      metadata:
        labels:
          homelab/backup-resource: "true"
      data:
        username: "${SECRET_CREDS_USER}"
        password: "{{ .password }}"
      engineVersion: v2
