---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: db-password-generator # Should reflect name in common library values
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      digits: 5
      symbols: 5
      symbolCharacters: "-_"
      noUpper: false
      allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password # Should reflect name in common library values
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      digits: 5
      symbols: 5
      symbolCharacters: "-_"
      noUpper: false
      allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: secret-key # Should reflect name in common library values
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
      digits: 10
      symbols: 5
      symbolCharacters: "-_"
      noUpper: false
      allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: api-key # Should reflect name in common library values
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      digits: 10
      symbols: 0
      symbolCharacters: ""
      noUpper: false
      allowRepeat: true