---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Role setup to allow the local ClusterSecretStore to operate
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  # Resources
  - clustersecretstore.yaml
  - clustergenerators.yaml
