---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
resources:
  - ./namespace.yaml
  - ./mariadb-cluster/ks.yaml
transformers:
  - ./transformers