apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${SECRET_KEY_NAME}
  labels:
    homelab/backup-resource: "true"
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: ${SECRET_KEY_TYPE:=secret-key}

  target:
    template:
      metadata:
        labels:
          homelab/backup-resource: "true"
      data:
        secretKey: "{{ .password }}"
      engineVersion: v2
