---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-barman-cloud
spec:
  releaseName: cnpg-barman-cloud
  chartRef:
    kind: OCIRepository
    name: cnpg-barman-cloud
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3

  values:
    # https://github.com/cloudnative-pg/charts/blob/main/charts/plugin-barman-cloud/values.yaml
    replicaCount: 1

    crds:
      create: true

    certificate:
      # # No TLS
      # createClientCertificate: false
      # createServerCertificate: false
      issuerName: homelab-issuer