---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
spec:
  releaseName: seafile
  # dependsOn:
  #   # Wait for DB resources and OIDC to be created
  #   - name: seafile-db
  #   - name: seafile-oidc
  chart:
    spec:
      chart: helm/apps/seafile
      interval: 12h
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    # - kind: Secret
    #   name: seafile-db-creds
    #   valuesKey: password
    #   targetPath: seafile.fluxcd.database.password
    - kind: Secret
      name: seafile-db-creds
      valuesKey: password
      targetPath: seafile.mariadb.password
    - kind: Secret
      name: mariadb-root-secret
      valuesKey: password
      targetPath: seafile.mariadb.rootPassword
    - kind: Secret
      name: seafile-jwt
      valuesKey: secretKey
      targetPath: seafile.fluxcd.jwtSecret
    - kind: Secret
      name: seafile-oidc-authentik-application
      valuesKey: clientID
      targetPath: seafile.fluxcd.oidc.clientId
    - kind: Secret
      name: seafile-oidc-authentik-application
      valuesKey: clientSecret
      targetPath: seafile.fluxcd.oidc.clientSecret

  # see https://github.com/truecharts/public/blob/master/charts/stable/sonarr/values.yaml
  # see documentation https://truecharts.org/charts/stable/sonarr/
  values:   
    seafile:
      authDomain: ${auth_subdomain}.${main_domain_websecure}
      serverDomain: ${SUBDOMAIN}.${main_domain_websecure}
      persistence:
        storage:
          server: ${nfs_server}
          path: ${nfs_path_seafile}

      workload:
        main:
          podSpec:
            initContainers:
              init:
                env: &seafile-env
                  SEAFILE_SERVER_HOSTNAME: ${SUBDOMAIN}.${main_domain}

            containers:
              main:
                env: *seafile-env