---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wakapi
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: wakapi
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: wakapi
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    - ../../../../../common/components/secret/key
  path: "./kubernetes/apps/base/services/wakapi/app"
  prune: true
  postBuild:
    substitute:
      APP: wakapi
      # Database
      PSQL_DB_USER: wakapi
      PSQL_DB_NAME: wakapi
      ## API key
      SECRET_KEY_NAME: wakapi-password-salt
      SECRET_KEY_TYPE: secret-key
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 5m
