---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zot
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: zot
  dependsOn:
    - name: s3-instance # Required for persistency
      namespace: operators
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: zot
      namespace: internal-ci
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/s3bucket
  path: "./kubernetes/platform/base/internal-ci/zot/app"
  postBuild:
    substitute:
      S3_USER: zot-${environment}
      BUCKET_NAME: zot
      BUCKET_QUOTA: "200000000000"
      # inherited variables
      environment: ${environment}
      minio_url: ${minio_url}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: internal-ci
  timeout: 5m
