---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
spec:
  releaseName: tekton-operator
  chart:
    spec:
      chart: charts/tekton-operator
      interval: 12h
      sourceRef:
        kind: GitRepository
        name: tekton-operator
      reconcileStrategy: Revision
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  postRenderers:
  - kustomize:
      patches:
        # Modify default observability configmap following these settings
        # https://tekton.dev/docs/pipelines/metrics/#configuring-metrics-using-config-observability-configmap
        - target:
            version: v1
            kind: ConfigMap
            name: tekton-operator-observability
          patch: |
            - op: add
              path: /data/metrics.backend-destination
              value: prometheus
            - op: add
              path: /data/metrics.request-metrics-backend-destination
              value: prometheus

  values:
    # see https://github.com/tektoncd/operator/blob/main/charts/tekton-operator/values.yaml
    installCRDs: true
    # tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonresult,tektondashboard,manualapprovalgate
    controllers: "tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektondashboard,manualapprovalgate"
    operator:
      defaultTargetNamespace: internal-ci

    podSecurityContext:
      fsGroup: 2000

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    
    service:
      createServiceMonitor: true