storage:
  size: 1Gi

mariadb:
  enableAntiAffinity: true
  image:
    repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
    # renovate: datasource=helm depName=mariadb-operator registryUrl=https://helm.mariadb.com/mariadb-operator
    tag: 25.10.1