---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-cluster
spec:
  releaseName: mongodb-cluster
  dependsOn:
    - name: mongodb-operator
      namespace: operators
  chart:
    spec:
      chart: helm/platform/mongodb-cluster
      interval: 12h
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  interval: 50m
  install:
    remediation:
      retries: 3

  values:
    storage:
      persistentClassName: ${fastdata_storage}
      size: 1Gi
      logsSize: 1Gi
    database:
      users:
        - tachi