{{/*
{{- $secretName := include "common.db.secret-name" (dict "DatabaseUser" .Values.config.db.user )}}
{{- include "common.db.extsecret" (dict "Namespace" .Release.Namespace "SecretName" $secretName "ClusterSecretName" .Values.database.postgres.clusterSecretName ) }}
*/}}