apiVersion: v2
name: legacyapps
description: Custom helm chart to expose legacy services on Kubernetes
dependencies:
  - name: common
    version: "0.0.1"
    repository: "file://../../library/common"
    import-values:
      - defaults
version: 0.0.1
