---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Role if watching only one namespace
metadata:
  name: authentik-blueprint-sidecar
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # RoleBinding if only one namespace
metadata:
  name: authentik-blueprint-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authentik-blueprint-sidecar
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: authentik