apiVersion: v2
name: zot
description: Zot Helm chart with resource provisioning
dependencies:
  - name: zot
    # Check version https://github.com/project-zot/helm-charts/releases
    version: &version 0.1.89
    repository: http://zotregistry.dev/helm-charts
  - name: common
    version: "0.0.1"
    repository: "file://../../library/common"
    import-values:
      - defaults
    # Other implicit dependencies are installed before this chart by fluxcd :
    # - s3-operator
version: *version
