---
# Variables : S3_USER, BUCKET_NAME, BUCKET_QUOTA (opt)
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - policy.yaml
  - s3user.yaml
  - bucket.yaml