---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  dependsOn:
    - name: ${APP}-oidc
  chartRef:
    kind: OCIRepository
    name: minio
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  # Patch only when local dns is used
  # Using postRenderers instead of patches in kustomizations, as variable substitution is not performed already
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: "${traefik_lb_ip}"
                    hostnames:
                    - "${auth_subdomain}.${main_domain}"
                    - "${second_domain}"
            target:
              kind: Deployment
              name: minio
              namespace: services
              annotationSelector: homelab/use-local-dns=true

  values:
    securityContext:
      container:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000

    workload:
      main:
        annotations:
          secret.reloader.stakater.com/auto: "true"
          homelab/use-local-dns: ${quote}${patch_dns:=false}${quote}
        podSpec:
          containers:
            main:
              env:
                MINIO_SERVER_URL: https://${SUBDOMAIN}.${DOMAIN_WEBSECURE}
                # Console URL
                MINIO_BROWSER_REDIRECT_URL: https://${ADMIN_SUBDOMAIN}.${DOMAIN_WEBSECURE}
                # OIDC for bucket administration
                MINIO_IDENTITY_OPENID_CONFIG_URL: https://${auth_subdomain}.${main_domain_websecure}/application/o/${APP}/.well-known/openid-configuration
                MINIO_IDENTITY_OPENID_CLIENT_ID:
                  secretKeyRef:
                    name: ${APP}-oidc-authentik-application
                    key: clientID
                    expandObjectName: false
                MINIO_IDENTITY_OPENID_CLIENT_SECRET:
                  secretKeyRef:
                    name: ${APP}-oidc-authentik-application
                    key: clientSecret
                    expandObjectName: false
                MINIO_IDENTITY_OPENID_CLAIM_USERINFO: https://${auth_subdomain}.${main_domain_websecure}/application/o/userinfo/
                MINIO_IDENTITY_OPENID_DISPLAY_NAME: Authentik
                MINIO_IDENTITY_OPENID_SCOPES: openid,profile,email,minio # minio is a property mapping managed in Authentik
                # Admin user
                MINIO_ROOT_USER:
                  secretKeyRef:
                    name: ${SECRET_CREDS_NAME}
                    key: username
                    expandObjectName: false

                MINIO_ROOT_PASSWORD:
                  secretKeyRef:
                    name: ${SECRET_CREDS_NAME}
                    key: password
                    expandObjectName: false


    persistence:
      config:
        enabled: true
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_minio}

    extraTpl:
      # Gateways
      - |
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: {{ .Release.Name }}-console
          namespace: {{ .Release.Namespace }}
        spec:
          parentRefs:
            - name: traefik-gateway
              namespace: ingress
              sectionName: websecure
              kind: Gateway

          hostnames:
            - ${ADMIN_SUBDOMAIN}.${main_domain}

          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /

              backendRefs:
              - name: {{ .Release.Name }}
                namespace: {{ .Release.Namespace }}
                port: {{ .Values.service.main.ports.main.port }}
      - |
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: {{ .Release.Name }}-api
          namespace: {{ .Release.Namespace }}
        spec:
          parentRefs:
            - name: traefik-gateway
              namespace: ingress
              sectionName: websecure
              kind: Gateway

          hostnames:
            - ${SUBDOMAIN}.${main_domain}

          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /

              backendRefs:
              - name: {{ .Release.Name }}-api
                namespace: {{ .Release.Namespace }}
                port: {{ .Values.service.api.ports.api.port }}