---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-pipelines
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tekton-pipelines
  dependsOn:
    - name: tekton-operator # We do need the pipeline engine to create our pipelines. Other dependencies are put in 
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tekton-pipelines
      namespace: internal-ci
  interval: 1h
  path: "./kubernetes/platform/base/internal-ci/tekton-pipelines/app"
  postBuild:
    substitute:
      # inherited variables
      git_repo_url: ${git_repo_url}
      git_branch: ${git_branch}
      fastdata_storage: ${fastdata_storage}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: internal-ci
  timeout: 5m
