---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  releaseName: cert-manager-webhook-ovh
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      # renovate: datasource=helm depName=cert-manager-webhook-ovh registryUrl=https://aureq.github.io/cert-manager-webhook-ovh
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: cert-manager-ovh-values-secrets
      valuesKey: email
      targetPath: issuers[0].email
    - kind: Secret
      name: cert-manager-ovh-values-secrets
      valuesKey: endpointName
      targetPath: issuers[0].ovhEndpointName
  values:
    # https://artifacthub.io/packages/helm/cert-manager-webhook-ovh/cert-manager-webhook-ovh?modal=values
    configVersion: 0.0.2
    certmanager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    replicas: 2

    topologySpreadConstraints:
      # Maximum 1 pod per Proxmox hypervisor
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: cert-manager-webhook-ovh
      # Maximum 1 pod per node. If only one worker remains, then only one replica is enough
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: cert-manager-webhook-ovh

    issuers:
      - name: letsencrypt
        acmeServerUrl: ${acme_server_url} # Inserted by FluxCD Terraform
        create: true
        kind: ClusterIssuer
        # Completed in valuesFrom
        # email: admin@example.com
        # ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: external-ovh-secrets
            key: applicationKey
          applicationSecretRef:
            name: external-ovh-secrets
            key: applicationSecret
          applicationConsumerKeyRef:
            name: external-ovh-secrets
            key: consumerKey