apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  releaseName: grafana-oidc
  chart:
    spec:
      chart: authentik-application
      # renovate: datasource=docker depName=authentik-application registryUrl=oci://codeberg.org/wrenix/helm-charts
      version: "0.4.9"
      sourceRef:
        kind: HelmRepository
        name: wrenix
        namespace: flux-system
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3

  values:
    # From https://codeberg.org/wrenix/helm-charts/src/branch/main/authentik-application/values.yaml
    blueprint:
      authentik:
        domain: "https://auth.${main_domain_websecure}"
      provider:
        enabled: true
        name: "Grafana"
        type: "oidc"
        oidc:
          clientType: "confidential"
          # clientID:
          # clientSecret:
          redirectURL: "https://monitoring.${main_domain_websecure}/login/generic_oauth"
          tokenDuration: "minutes=5"
          signingKey: "namespace_authentik.secret_authentik-cert-tls.tls"
          scopes:
            - name: "authentik default OAuth Mapping: OpenID 'openid'"
            - name: "authentik default OAuth Mapping: OpenID 'email'"
            - name: "authentik default OAuth Mapping: OpenID 'profile'"
            # - name:
            #   scope_name:
            #   expression:
      application:
        name: "Grafana"
        slug: "grafana"
        group: "Admin"
        launchURL: "https://monitoring.${main_domain_websecure}"
        openInNewTab: false
        icon: ""
        description: "Monitoring system"
        bindPolicyID:
        policyEngineMode: "any"
      groups: []      #

      
