---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kavita
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kavita
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kavita
      namespace: media
  interval: 1h
  path: "./kubernetes/apps/base/media/kavita/app"
  postBuild:
    substitute:
      # inherited variables
      fastdata_storage: ${fastdata_storage}
      nfs_server: ${nfs_server}
      nfs_path_download: ${nfs_path_download}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 10m
