---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-utils
resources:
  - ./namespace.yaml
  - ./descheduler/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  # - ./proxmox-csi-plugin/ks.yaml
transformers:
  - ./transformers