---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crowdsec
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: crowdsec
  dependsOn:
    - name: psql-cluster
      namespace: ${psql_database_namespace}
    - name: traefik-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: crowdsec
      namespace: ingress
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    - ../../../../../common/components/secret/key
  path: "./kubernetes/platform/base/ingress/crowdsec/app"
  prune: true
  postBuild:
    substitute:
      APP: crowdsec
      ## Database
      PSQL_DB_USER: crowdsec
      PSQL_DB_NAME: crowdsec
      ## API key
      SECRET_KEY_NAME: crowdsec-lapi-key
      SECRET_KEY_TYPE: secret-key
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ingress
  timeout: 10m
