apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-oidc
  namespace: services
spec:
  releaseName: gitea-oidc
  dependsOn:
    - name: authentik
      namespace: authentik
  chart:
    spec:
      chart: authentik-application
      # renovate: datasource=docker depName=authentik-application registryUrl=oci://codeberg.org/wrenix/helm-charts
      version: "0.4.9"
      sourceRef:
        kind: HelmRepository
        name: wrenix
        namespace: flux-system
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3

  values:
    # From https://codeberg.org/wrenix/helm-charts/src/branch/main/authentik-application/values.yaml
    blueprint:
      authentik:
        domain: "https://auth.${main_domain_websecure}"
      provider:
        enabled: true
        name: "Gitea"
        type: "oidc"
        oidc:
          clientType: "confidential"
          redirectURL: "https://gitea.${main_domain_websecure}/user/oauth2/Authentik/callback"
          signingKey: "namespace_authentik.secret_authentik-cert-tls.tls"
          tokenDuration: "minutes=5"
          scopes:
            - name: "authentik default OAuth Mapping: OpenID 'openid'"
            - name: "authentik default OAuth Mapping: OpenID 'email'"
            - name: "authentik default OAuth Mapping: OpenID 'profile'"
      application:
        name: "Gitea"
        slug: "gitea"
        group: "Services"
        launchURL: "https://gitea.${main_domain_websecure}"
        openInNewTab: false
        icon: ""
        description: "Git server"
        bindPolicyID:
        policyEngineMode: "any"
      groups:
        - slug: "app: gitea"
          parent: "authentik Admins"
          bindID: "53c0fd0e-9d9f-4825-b7a0-9ff505a28a91" # arbitrary uuid
