---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jdownloader2
spec:
  releaseName: jdownloader2
  dependsOn:
    - name: ${APP}-proxy
  chartRef:
    kind: OCIRepository
    name: jdownloader2
  interval: 50m
  install:
    createNamespace: true
    remediation:
      retries: 3
  # see https://github.com/truecharts/public/blob/master/charts/stable/jdownloader2/values.yaml
  values:
    resources:
      limits:
        cpu: 500m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 400Mi
    securityContext:
      pod:
        fsGroup: 1000
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 1000

    jdownloader:
      DISPLAY_WIDTH: 1680
      DISPLAY_HEIGHT: 800
    
    workload:
      main:
        strategy: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
    
    # configmap:
    #   jdownloader:
    #     data:
    #       USER_ID: "1000"
    #       GROUP_ID: "1000"

    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: "/config"
      output:
        enabled: true
        type: nfs
        server: ${nfs_server}
        path: ${nfs_path_download}
        mountPath: "/output"