---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: snapshot-controller
  dependsOn:
    # Needs monitoring CRDs as it is required by some options
    - name: prometheus-crds
      namespace: opentelemetry
    # Requires external-secrets clustersecretstore to create externlsecrets for s3 access
    - name: external-secrets
      namespace: external-secrets
    # Also requires piraeus operator to be deployed
    - name: piraeus-operator
      namespace: piraeus-datastore
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: snapshot-controller
      namespace: system-backup
  interval: 1h
  path: "./kubernetes/platform/base/system-backup/snapshot-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system-backup
  timeout: 5m