{{- $domainSplit := include "common.func.split-externalurl" (dict "Domain" .Values.app.controllers.opencloud.containers.app.env.OC_URL) | fromJson }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: {{ ternary "websecure" "web" (eq $domainSplit.Protocol "https")}}
      kind: Gateway

  hostnames:
    - {{ $domainSplit.Domain }}

  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /

      backendRefs:
      - name: opencloud
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.app.service.app.ports.http.port }}