---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./namespace.yaml
  - ./traefik-middlewares/ks.yaml
  - ./flaresolverr/ks.yaml
transformers:
  - ./transformers