---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: s3-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: s3-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: s3-operator
      namespace: operators
  interval: 1h
  path: "./kubernetes/platform/base/operators/s3-operator/app"
  # postBuild:
  #   substitute:
  #     # inherited variables
  #     minio_url: ${minio_url}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: operators
  timeout: 10m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: s3-instance
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: s3-instance
  dependsOn:
    - name: s3-operator
  healthChecks:
    - apiVersion: s3.onyxia.sh/v1alpha1
      kind: S3Instance
      name: default
      namespace: operators
  healthCheckExprs:
    - apiVersion: s3.onyxia.sh/v1alpha1
      current: status.conditions.filter(e, e.type == 'Reconciled').all(e, e.status == 'True')
      inProgress: status.conditions.filter(e, e.type == 'Reconciled').all(e, e.status == 'False')
      kind: S3Instance
  interval: 1h
  path: "./kubernetes/platform/base/operators/s3-operator/instance"
  postBuild:
    substitute:
      # inherited variables
      minio_url: ${minio_url}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: operators
  timeout: 10m