---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver
resources:
  - ./namespace.yaml
  - ./kubelet-cert-approver/ks.yaml
transformers:
  - ./transformers