---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: tuppr
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tuppr
      namespace: system-upgrade
  interval: 1h
  path: "./kubernetes/system/base/system-upgrade/tuppr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system-upgrade
  timeout: 10m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tuppr
  dependsOn:
    - name: tuppr
  interval: 1h
  path: "./kubernetes/system/base/system-upgrade/tuppr/upgrades"
  prune: true
  postBuild:
    substitute:
      # inherited variables
      psql_database_namespace: ${psql_database_namespace}
      psql_cluster_name: ${psql_cluster_name}
      psql_suffix: ${quote}${psql_suffix:=}${quote}
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system-upgrade
  timeout: 5m
  wait: false