---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: seerr
  dependsOn:
    - name: sonarr
    - name: radarr
    - name: radarr4k
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: seerr
      namespace: media
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    # - ../../../../../common/components/httproute/common # TODO : enable this again when we finished to setup seerr
    - ../../../../../common/components/secret/key
  path: "./kubernetes/apps/base/media/seerr/app"
  postBuild:
    substitute:
      APP: seerr
      SUBDOMAIN: requests
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      # TODO : other subdomain variables ?
      ## Database
      PSQL_DB_USER: seerr
      PSQL_DB_NAME: seerr
      ## Gateway
      GATEWAY_SVC_NAME: seerr
      GATEWAY_SVC_PORT: "10241"
      ## API key
      SECRET_KEY_NAME: seerr-api-key
      SECRET_KEY_TYPE: api-key
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
      fastdata_storage: ${fastdata_storage}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 10m
