---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tekton-operator
  dependsOn:
    - name: zot # We need a registry to start pushing our container images
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tekton-operator
      namespace: internal-ci
  interval: 1h
  path: "./kubernetes/platform/base/internal-ci/tekton-operator/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: internal-ci
  timeout: 5m
