---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: vaultwarden
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vaultwarden
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/cnpg/db
    - ../../../../../common/components/httproute/common
  path: "./kubernetes/apps/base/services/vaultwarden/app"
  postBuild:
    substitute:
      APP: vaultwarden
      SUBDOMAIN: vault
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      PSQL_DB_USER: vaultwarden
      PSQL_DB_NAME: vaultwarden
      GATEWAY_SVC_NAME: vaultwarden
      GATEWAY_SVC_PORT: "10102"
      # inherited variables
      psql_cluster_name: ${psql_cluster_name}
      psql_database_namespace: ${psql_database_namespace}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 5m
