---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3-operator
spec:
  releaseName: s3-operator
  chart:
    spec:
      chart: s3-operator
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: inseefrlab
  interval: 50m
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace

  values:
    # see https://github.com/InseeFrLab/s3-operator/blob/main/deploy/charts/s3-operator/values.yaml
    crds:
      install: true
      keep: true # true for persistency

    controllerManager:
      replicas: 2
      # manager:
      #   resources:
      #     limits:
      #       cpu:
      #       memory:
      #     requests:
      #       cpu:
      #       memory:
      # manager:
        # image: # workaround for: https://github.com/InseeFrLab/helm-charts/issues/84
        #   tag: v0.11.0 
        # extraArgs:
        #   - --useSsl=false

    kubernetes:
      overrideExistingSecret: true

    s3:
      default:
        # We need to deploy it manually as it conflicts with the CRD deployment...
        enabled: false
        # createNamespace: false
        # s3Provider: minio
        # namespace:
        # url: http://${minio_url}
        # secretRef: minio-external-secret

        # # accessKey: ""
        # # secretKey: ""

        # region: ""
        # deletion:
        #   bucket: false
        #   path: false
        #   policy: true
        #   s3user: true
