---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencloud-oidc
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: opencloud
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: opencloud-oidc
      namespace: services
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: opencloud-desktop-oidc
      namespace: services
  interval: 1h
  path: "./kubernetes/apps/base/services/opencloud/oidc"
  postBuild:
    substitute:
      SUBDOMAIN: drive
      # inherited variables
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
      auth_subdomain: ${auth_subdomain}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 10m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencloud
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: opencloud
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: opencloud
      namespace: services
  interval: 1h
  components:
    # relative to spec.path
    - ../../../../../common/components/s3bucket
    - ../../../../../common/components/httproute/common
    - ../../../../../common/components/secret/creds
  path: "./kubernetes/apps/base/services/opencloud/app"
  postBuild:
    substitute:
      APP: opencloud
      SUBDOMAIN: drive
      DOMAIN: ${main_domain}
      DOMAIN_WEBSECURE: ${main_domain_websecure}
      ## S3 storage
      S3_USER: opencloud-${environment}
      BUCKET_NAME: opencloud-${environment}
      ## Gateway
      GATEWAY_SVC_NAME: opencloud
      GATEWAY_SVC_PORT: "80"
      ## Generated secrets
      SECRET_CREDS_NAME: opencloud-admin-creds
      SECRET_CREDS_USER: admin
      # inherited variables
      quote: '"'
      patch_dns: ${quote}${patch_dns:=false}${quote}
      traefik_lb_ip: ${traefik_lb_ip}
      main_domain: ${main_domain}
      main_domain_websecure: ${main_domain_websecure}
      second_domain: ${second_domain}
      auth_subdomain: ${auth_subdomain}
      environment: ${environment}
      minio_url: ${minio_url}
      fastdata_storage: ${fastdata_storage}

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 10m
