apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dragonfly
  - ../base/ingress
  - ../base/internal-ci
  # - ../base/mariadb
  # - ../base/mongodb
  - ../base/monitoring
  - ../base/operators
  - ../base/postgres
  - ../base/velero
