---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-operator-crds
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: victoria-metrics-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-metrics-operator-crds
      namespace: monitoring
  interval: 1h
  path: "./kubernetes/platform/base/monitoring/victoriametrics-operator/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: victoria-metrics-operator
  dependsOn:
    - name: victoria-metrics-operator-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-metrics-operator
      namespace: monitoring
  interval: 1h
  path: "./kubernetes/platform/base/monitoring/victoriametrics-operator/app"
  postBuild:
    substitute:
      fastdata_storage: ${fastdata_storage}
      influxdb_lb_ip: ${influxdb_lb_ip}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 10m